### ISSUE TITLE
Create Splash Page

### ISSUE THREAD

**Issue by ghost** [redacademy/fed-fall-2016#12]

**Comment by ghost** [comment]
Helpful resource:
https://github.com/remobile/react-native-splashscreen

**Comment by ShMcK** [comment]
A simple image solution for IOS:  https://medium.com/the-react-native-log/change-default-launch-screen-in-react-native-ios-app-544f94f1e947#.gdfhk7igl

**Comment by ShMcK** [comment]
Android solution: https://android.jlelse.eu/change-splash-screen-in-react-native-android-app-d3f99ac1ebd1#.r84qkiaxp
